# Generated by Django 3.0.4 on 2020-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200309_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
